/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./components/Footer.vue')['default']
    Ground: typeof import('./components/Ground.vue')['default']
    MouseParallax: typeof import('./components/MouseParallax.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    RadioCards: typeof import('./components/RadioCards.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Vehicle: typeof import('./components/Vehicle.vue')['default']
    VehicleShow: typeof import('./components/VehicleShow.vue')['default']
  }
}
